### ISSUE TITLE
Requires admin privileges even tho it was ran as administrator

### ISSUE THREAD

**Issue by seemsindie** [be5invis/vscode-custom-css#107]
Hello, I ran VS Code as an administrator, and when I try to run "Enable custom CSS and JS" I get this message "Run VS Code with admin privileges so the changes can be applied.".

I am using Windows 10 build 19041.1 

Any ideas why is this happening or is it a bug?

Thanks

![image](https://user-images.githubusercontent.com/1268576/71328350-057fef00-2516-11ea-83e0-34d867ca69e6.png)

**Comment by heymajor** [comment]
I had the same issue with WSL, but it worked after I closed the remote connection and tried it again with the local installation. 

You'll get an 'corrupted VScode install' error on reload, but the extension suggests to mute the warning instead of reinstalling. 

Also: Because it doesn't work from WSL, it might be easier to put the CSS file in a Windows folder and use the Windows path (file:///C:/...)
