### ISSUE TITLE
root staging of css when enabled with sudo permissions?

### ISSUE THREAD

**Issue by mmattocks** [be5invis/vscode-custom-css#137]
Hello! Since the v5. change, I have not been able to reload custom CSS as usual. Normally I run `sudo code --user-data-dir="/home/main/.config/Code/"`, run "reload custom css", and restart with permissions using the popup gui.  When I do this since v5., the css file is applied correctly in the sudo instance, but when started normally, the Log (Main) reads:

```
[2021-03-06 09:59:00.768] [main] [error] file: Refused to load resource /root/.vscode/extensions/be5invis.vscode-custom-css-5.0.1/src/statusbar.js from file: protocol (original URL: file:///root/.vscode/extensions/be5invis.vscode-custom-css-5.0.1/src/statusbar.js)
[2021-03-06 09:59:00.769] [main] [error] file: Refused to load resource /root/.vscode/extensions/be5invis.vscode-custom-css-5.0.1/.staging-custom-css/8a05ddcb-5475-482b-985b-fb85dfb326c5/e6465485-94ae-41a3-8caa-e00837c7c870.css from file: protocol (original URL: file:///root/.vscode/extensions/be5invis.vscode-custom-css-5.0.1/.staging-custom-css/8a05ddcb-5475-482b-985b-fb85dfb326c5/e6465485-94ae-41a3-8caa-e00837c7c870.css)
```

'/root/.vscode' doesn't exist.

**Comment by Kikobeats** [comment]
I'm facing this.

Since v5.0.2 the logic added by @be5invis for copying the file is working, but then looks like the editor can load the file properly:

<img width="943" alt="Screen Shot 2021-03-06 at 18 00 34" src="https://user-images.githubusercontent.com/2096101/110214651-e284f500-7ea5-11eb-8324-b920447d1c1a.png">

<img width="1438" alt="Screen Shot 2021-03-06 at 18 00 28" src="https://user-images.githubusercontent.com/2096101/110214653-e57fe580-7ea5-11eb-8b86-bf245eaa73bd.png">

Look how both files exist but the network call can't be resolved – I'm under macOS.

**Comment by Kikobeats** [comment]
I'm not sure how practical could be this, but instead of injecting the script on the HTML markup:

https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js#L179

I did a workaround to inject all the file content:

```
return `<style>${fetched.toString()}</style>\n`
```

and now it's working since the error is happening when the browser try to load the external content

**Comment by be5invis** [comment]
I just pushed a patch version to make the logic of deciding the staging directory more reliable. And it also made it configurable: configuration `vscode_custom_css.staging_dir` will override the built-in value.

**Comment by mmattocks** [comment]
God protect and preserve you, I have -3 to coding morale checks without this extension. I ended up using the override variable, which worked fine, but, for anyone who also needs this, it shouldn't be set to the extensions/ directory itself, or the root permissioned instance will wipe out the .css and give extensions/ root permissions. Thanks very much for the fix!!!
