### ISSUE TITLE
Better explanation of what this plugin does?

### ISSUE THREAD

**Issue by iankkhoros** [be5invis/vscode-custom-css#159]
- I am unable to figure out what this plugin does based on the description. Can you add a simple paragraph about what this is supposed to do?
- Also, it could use more clarity in how to use it. 
- "VERY IMPORTANT: Items in vscode_custom_css.imports must be URLs. Plain file paths are NOT URLs." could use some examples. What is vscode_custom_css.imports, why and how would I modify it? 
- Where is a lis of style names to modify? Or JS?

**Comment by robregan** [comment]
it's for using custom css inside of VScode. I tried using it to get the "glowing effect" of the Synthwave '84 extension, but can't seem to find the custom css file. 
 - plain file path for that certain extension would look like `file:///C:/Users/{yourUsername}/.vscode/extensions/webrender.synthwave-x-flouromachine-0.0.12/synthwave-x-flouromachine.css` and a URL would look more like `http://localhost:3000/{whatever} //or your ip adress instead of localhost`
 - You can edit the settings.json in VScode by `control/cmd + shift + p //to open command pallet` then search for Open Settings (JSON) to add whatever you'd like

**Comment by iankkhoros** [comment]
Thank you
