### ISSUE TITLE
doesn't work and always show "file:///home/yourname/.vscode/custom.css Failed to load resource: net::ERR_FILE_NOT_FOUND"

### ISSUE THREAD

**Issue by gxy01** [be5invis/vscode-custom-css#3]
my setting.json  is:
`        "vscode_custom_css.imports": [
        "file:///Users/gxy/.vscode/custom.css"
    ]
`
the console always show :
    
    file:///home/yourname/.vscode/custom.css Failed to load resource: net::ERR_FILE_NOT_FOUND。

I also tried online style, but they doesn't work either.
The OS is macOS

**Comment by be5invis** [comment]
What is your full user settings?
You may have duplicate settings in the file.

**Comment by gxy01** [comment]
I already checked both settings in my projectpath and workspace, but can't solve this. At the end I reinstall the vscode and the plugin, it 's worked.
Thanks for your plugin, it's really awesome.

**Comment by be5invis** [comment]
Closed as solved.

**Comment by 3DEsprit** [comment]
I have run into this issue as well on OSX. 

I removed everything from user and workspace settings except for the imports, removed and reinstalled the extension, with no resolve. The permissions and ownership of the file itself is fine (644), and I am using the same import URL in the array that I used when it did work. Just to make sure, I navigated to the file via the CLI and used _pwd_ to check for typo errors in the file location. 

One odd issue is that if I use file:/// instead of file://, the error still says it cannot find "file://users/whoami/...."

The error location also changed on me recently to something very odd:

![error](https://cloud.githubusercontent.com/assets/3156278/24469791/573efeaa-1482-11e7-94e0-9df22eb183a4.png)

I will reinstall later on, but I wanted to at least bring it up while it is still an error on my system.

**Comment by be5invis** [comment]
Mac uses capitalized "/Users/". I saw yours is in lower case.

发自我的 iPhone

在 2017年3月30日，02:20，Dennis Brown <notifications@github.com<mailto:notifications@github.com>> 写道：


I have run into this issue as well on OSX.

I removed everything from user and workspace settings except for the imports, removed and reinstalled the extension, with no resolve. The permissions and ownership of the file itself is fine (644), and I am using the same import URL in the array that I used when it did work. Just to make sure, I navigated to the file via the CLI and used pwd to check for typo errors in the file location.

One odd issue is that if I use file:/// instead of file://, the error still says it cannot find "file://users/whoami/...."

The error location also changed on me recently to something very odd:

[error]<https://cloud.githubusercontent.com/assets/3156278/24469791/573efeaa-1482-11e7-94e0-9df22eb183a4.png>

I will reinstall later on, but I wanted to at least bring it up while it is still an error on my system.

**Comment by 3DEsprit** [comment]
Yes, I should have mentioned that the path is added in the correct case, but OSX is only explicitly case-sensitive when using the journaled file-system. The default non-journaled NFS+ allows multiple-cased file naming, but is not case sensitive when accessing files.  Even with that said, it seems that this path is being normalized as it is loaded.

**Comment by ibenettaleb** [comment]
Changed to :

```
file:///C:/Users/dbrown/Documents/VSCode/styles.css
```
