### ISSUE TITLE
Cannot load css from gist.github.com

### ISSUE THREAD

**Issue by Kasperfred** [be5invis/vscode-custom-css#30]
Attempting to load css from a Github gist results in the following error:

```
Refused to load the stylesheet 'https://gist.githubusercontent.com/Kasperfred/212a0d765f046d9bf837d3a2292649b4/raw/1e1cb7dfac8d43f5c5e66dfe82bf3dfc75b240b1/editor.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'".
```

**Comment by be5invis** [comment]
I cannot prevent Code from applying CSP. Please file an issue to the Code team or download the file to local host.

发自我的 iPhone

在 2018年2月5日，04:27，Kasper Fredenslund <notifications@github.com<mailto:notifications@github.com>> 写道：


Attempting to load css from a Github gist results in the following error:

Refused to load the stylesheet 'https://gist.githubusercontent.com/Kasperfred/212a0d765f046d9bf837d3a2292649b4/raw/1e1cb7dfac8d43f5c5e66dfe82bf3dfc75b240b1/editor.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'".

**Comment by be5invis** [comment]
Closed as fixed.
