### ISSUE TITLE
google drive https download not working.

### ISSUE THREAD

**Issue by cosmoKenney** [be5invis/vscode-custom-css#37]
VSCode version: 1.21.1
Custom css extension version: 2.7.0

User settings:
```
    "vscode_custom_css.policy": true,
    "vscode_custom_css.imports": [
        "https://drive.google.com/uc?export=download&id=1DVecHx1w2yL3NtsYIJA5tUhpKl7cFGeA"
    ],
```
If I place the css file in my file system and use a file:// path, then it works. 

I have used the enable and reload commands. I have closed and reopened VS Code. 

I really need this to work because I use the CodeSync extension on different computers and my google drive path is different on those computers. So keeping the custom css in the google drive path doesn't work because the CodeSync extension pulls in a shared user settings.json file.

**Comment by be5invis** [comment]
cc. @Kasperfred
HTTP(S) support is made by him.

**Comment by Kasperfred** [comment]
@cosmoKenney It doesn't work because the extension naïvely sends a get request, and doesn't attempt to manage file downloads which is what the Google drive link wants you to do. 

Case in point, when I curl the url, I get: 
```
hermes:~ kasperfred$ curl https://drive.google.com/uc?export=download&id=1DVecHx1w2yL3NtsYIJA5tUhpKl7cFGeA
[1] 19905
hermes:~ kasperfred$ <HTML>
<HEAD>
<TITLE>Bad Request</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Bad Request</H1>
<H2>Error 400</H2>
</BODY>
</HTML>
```
Since the HTML here is all the extension sees, it explains why it doesn't work. 

It's designed this way as I thought the primary use case would be people serving the CSS with a web server, or using managed hosting such as Github.

Anyway, in order to fix it, you can put your CSS in a [gist](https://gist.github.com/), and then give vscode with the "raw" link found next to the filename. 

<img width="984" alt="screen shot 2018-03-17 at 11 15 47 am" src="https://user-images.githubusercontent.com/13367236/37554116-9b9e7360-29d4-11e8-83be-c556f9f2d4d5.png">

**Comment by be5invis** [comment]
Close as invalid.
