### ISSUE TITLE
Doc: provide a more DETAILED instructions.

### ISSUE THREAD

**Issue by SheepDomination** [be5invis/vscode-custom-css#41]
Sorry, how do I begin to use this extension ? 
I've read over the *extension commands* but still don't understand how to actually begin to use this extension.

**Comment by be5invis** [comment]
I think there are very detailed instructions in other issues. The closed ones.

发自我的 iPhone

在 2018年5月22日，02:01，SheepDomination <notifications@github.com<mailto:notifications@github.com>> 写道：


Sorry, how do I begin to use this extension ?
I've read over the extension commands but still don't understand how to actually begin to use this extension.

**Comment by be5invis** [comment]
From other issues

———

1. Install this extension.
2. Add to `settings.json`:

```json
    "vscode_custom_css.imports": [""],
    "vscode_custom_css.policy": true,
```

3. Pay attention:

`file://` + `/User/yourname/path/to/css` = `file:///User/yourname/path/to/css`

Then here is: `"vscode_custom_css.imports": ["file:///User/yourname/path/to/css"],`

3. Close the VSCode and open the terminal and run it with root / admin permission.
4. Open VSCode, "Reload CUSS CSS and JS".
5. Restart.
6. Voilà.

**Comment by be5invis** [comment]
In user settings you should write things like:

    "vscode_custom_css.imports": ["file:///User/yourname/path/to/css"]

The reason is that the items **must be proper URLs.** File paths are not URLs.

**Comment by SheepDomination** [comment]
Can this work `"vscode_custom_css.imports": [
        "vscode_custom_css.imports": ["file:///C:/Custom Program Settings/vscode_settings/uivscode.css"]
    ],` ?
I'm getting an error ?

**Comment by be5invis** [comment]
What is the error?
Before running the “enable” command you must fully restart VSCode in Admin permission.

**Comment by be5invis** [comment]
"vscode_custom_css.imports": ["file:///C:/Custom Program Settings/vscode_settings/uivscode.css"]
This should work if your file is really there.

**Comment by SheepDomination** [comment]
The error is from within the `user settings` in the line I posted and that error is; `expected comma` ?

**Comment by be5invis** [comment]
I think you should learn the format of JSON... User settings file is a JSON.
Screenshot of that “error”?

**Comment by SheepDomination** [comment]
I fixed the error; deleted the question

**Comment by SheepDomination** [comment]
What do you mean `Reload CUSS CSS and JS`; isn't restarting VSCode reloading the extension ?
The problem with starting VSCode in administrator mode is the previous session is not loaded.

**Comment by be5invis** [comment]
@SheepDomination I've updated the README.
You need to:
 1. Restart VSCode program. Close all the windows and restart with **admin permission**.
 2. Press `F1`, type `Reload Custom CSS and JS`. You would see a message.
 3. Close all the windows again. Restart VSCode normally.
 4. After that, you would see a message "VSCode installation is broken". Press "Ignore". And you would see a bucket icon on the status bar, which means the plugin is working.

**Comment by be5invis** [comment]
God. Have you ever installed the extension??? The command name is exactly “Reload Custom CSS and JS”. Or could you find “Enable Custom CSS and JS”??? Have you ever used VSCode???

**Comment by be5invis** [comment]
Include @gusbemacbe
I know you are good at writing docs and instructions. PRs are really welcome. We need a **very detailed** instructions that even for a person **never used VSCode** and **never wrote any program**, he can also follow and customize his VSCode.

**Comment by be5invis** [comment]
@SheepDomination 
Do you need a video for this? I can record one later if you cannot understanding my words.

**Comment by SheepDomination** [comment]
Of course I have the extension installed, I wouldn't go though all this if the extension wasn't installed.

**Comment by SheepDomination** [comment]
![code_2018-05-21_21-49-36](https://user-images.githubusercontent.com/6827459/40338022-eb0a1d60-5d40-11e8-808f-d88a9652b526.png)

**Comment by be5invis** [comment]
You typed an extra space?

**Comment by SheepDomination** [comment]
Nope

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/40338129-fc59dea6-5da5-11e8-8f50-8ae5e3409a5e.png)
↑ On my system.

Could you please open the Dev tools (in the `Help` menu on the menu bar), and show whether there are any error messages?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/40338193-5944975a-5da6-11e8-85f5-76a0c2b5db30.png)
This one should be here and should be enabled (shown like in the image. Not grayed out.)

**Comment by SheepDomination** [comment]
Found the problem.

**Comment by SheepDomination** [comment]
I knew the problem was with you hard coding in requiring administrator privileges. 

It works when I don't run VSCode as an Administrator **but** when running the command `Reload custom CSS and JS` not as an Administrator it doesn't work because it needs Administrator rights; arGghh.

**Comment by gusbemacbe** [comment]
I own Windows and I'll analyse VSCode and the extension on Windows and I'll update the instructions.

Maybe @SheepDomination has forgotten of making VSCode as user instead of admin/root. 

When my instructions on Windows work, I'll fork the extension, reorganise README and the instructions for MacOS, Linux and Windows users.

**Comment by gusbemacbe** [comment]
@SheepDomination, we need to know and see your CSS code if they are supported by VSCode.

**Comment by SheepDomination** [comment]
@gusbemacbe The instructions could use a little work; but there not horrible either 👍 
I don't run any problems in Administration mode in Windows, if programs require Administrator I'm prompt.  This option within the extension should be toggled.

**Comment by be5invis** [comment]
@SheepDomination 
Wait. When Code is launched with Admin permissions the extension is not loaded???
Admin is required because the extension modifies Code itself.

**Comment by SheepDomination** [comment]
@be5invis 

> Wait. When Code is launched with Admin permissions the extension is not loaded???

That is correct.

**Comment by be5invis** [comment]
@SheepDomination 
Administrator permission is required because the only way to make Code load arbitrary CSS is to modify itself.
What is your Operating System, Code version, and are there any messages on the Dev tools when launched with Admin permissions??????

**Comment by SheepDomination** [comment]
@gusbemacbe I have confidence my css is supported. There is only one way to write CSS 👍 
@be5invis **Windows10** `(1709)` **Code** `(1.23.0)` *No* messages within Dev Tools when VSCode is run as an Administrator.

**Comment by be5invis** [comment]
@SheepDomination 

This is my system, same OS and Code version, extension from the Store. It is loaded in admin permissions.
I suggest you uninstall the extension by directly delete it from `%USERPROFILE%/.vscode/exensions`, and reinstall it, and see whether it loads in Admin mode.

![image](https://user-images.githubusercontent.com/240091/40338561-5f53704c-5da8-11e8-8e06-4fb8d921c65c.png)

**Comment by SheepDomination** [comment]
@be5invis Same problem.

**Comment by SheepDomination** [comment]
When running VS Code **not** as an Administrator I can access the command; you may want to change so the extension can write to non-Administrator.  You assume all users run as Administrator instead of Standard user.

**Comment by SheepDomination** [comment]
@be5invis True; but I'll do my other method and follow up for anyone else whom may run into this with your extension. 👍

**Comment by be5invis** [comment]
@gusbemacbe This is the first time I met a "standard user". Maybe he is under some domain I think.
@SheepDomination For "Standard Users", launching Code with Admin permissions would use another set of extensions.
Please note that the values of `vscode_custom_css.imports` would be directly baked into Code's installation so all accounts would share one config. The last one who baked Code would affect all the accounts on your computer. However this is unsolvable since Code itself does not provide any direct interface to load arbitrary CSS.

**Comment by gusbemacbe** [comment]
I am only an administrator user of WIndows. I will create a standard user to analyse the VSCode and the extension, if both work on admin and standard user accounts, I will fork your extension and reorganise the instructions.

**Comment by SheepDomination** [comment]
@gusbemacbe Yes try it, in the meantime I'll have to grant access to folders for VSCode.

**Comment by gusbemacbe** [comment]
I spent hours, trying to command via terminal, but I had to use Chocolatey and Cygwin because without them, it requires a lot of job and hours, so DOS is very complicated than Unix. To hybridise DOS with Unix commands to give standard user powers to VSCode, you need to use Chocolatey and Cywin.

On Windows, `"vscode_custom_css.imports": ["file:///Users/Gustavo%20Costa/.vscode/themes/nordic.css"],` works well. But when you restart the app as administrator or after running `chmod -R 777  /cygdrive/c/Program\ Files/Microsoft\ VS\ Code` or `chown-R $(whoami) /cygdrive/c/Program\ Files/Microsoft\ VS\ Code` and reload VSCode, the bucket icon is visible, but the CSS is not reloaded, although the URL path be correct. 

Because there is a file which is exclusively owned by an unknown called TrustedInstaller. You can see the screenshot:

![image](https://user-images.githubusercontent.com/2257024/40344363-d8fe724a-5d6a-11e8-8704-35ebc85c43ce.png)

I remember the problems of Atom users with PHP Codesniffer and I will check the URL that the guy provided.

**Comment by gusbemacbe** [comment]
After reading the topics of PHP Formatter and Markdown styling repositories issues, computer's URLs on VSCode on Windows are not supported due to restriction, read @mjbvz's comment. Maybe @bpasero, @Tyriar, and @sandy081 know, but I guess they will say it is not supported on Windows. 

**References:**
https://github.com/Microsoft/vscode/issues/45260
https://github.com/Microsoft/vscode/issues/45563
https://github.com/Microsoft/vscode/issues/47055
https://github.com/Microsoft/vscode/issues/47068
https://github.com/neilsustc/vscode-markdown/issues/118

Only Linux and macOS users are lucky. 

Who is user of Windows 10 and VSCode and wants to style VSCode body, I recommend WSL. I run VSCode on Kali Linux as WSL, on Windows, using this extension and CSS file.

**Comment by gusbemacbe** [comment]
I also commanded `icacls`, but "Gustavo Costa:F" is hard to be recognised by `icacls` due to space.

**Comment by be5invis** [comment]
Or use `set-acl` in Powershell. This gives more precise control.

**Comment by be5invis** [comment]
`"vscode_custom_css.imports": ["file:///Users/Gustavo%20Costa/.vscode/themes/nordic.css"]`
Well, you need `file:///C:/......`

**Comment by gusbemacbe** [comment]
As you have suggested, I readjusted and it worked **without running as administrator**. The key is giving standard user power to VSCode, using Chocolatey and Cygwin.

**Comment by SheepDomination** [comment]
@gusbemacbe Chocolatey and Cygwin must be used together to allow VSCode to run as an Administrator in a Standard account or can I just use Cygwin ? 
Doesn't that write the setting files for *vscode-custom-css* to an Administrator account, rather then the standard account, which is preferred ?

**Comment by be5invis** [comment]
> Doesn't that write the setting files for vscode-custom-css to an Administrator account, rather then the standard account, which is preferred ?
Yes.

**Comment by SheepDomination** [comment]
I got it working. 

The best solution, run VSCode as an Administrator, install `vscode-custom-css` apply your settings to `settings.json` file, restart VSCode as an Administrator; then run `Reload Custom CSS & JS`. Everything will work successfully, now restart VS Code as you would, as a Standard user.

**Comment by Dinosaurum** [comment]
> From other issues
> 
> ———
> 
> 1. Install this extension.
> 2. Add to `settings.json`:
> 
> ```json
>     "vscode_custom_css.imports": ["file:///path/to/your/style.css"],
>     "vscode_custom_css.policy": true,
> ```
> 
> **Important:** items in `vscode_custom_css.imports` must be **Proper URLs**. **Plain File paths, without `file:///` prefixe are NOT URLs.**
> 
> 3. Close the VSCode and open the terminal and run it with root / admin permission.
> 4. Open VSCode, "Reload CUSS CSS and JS".
> 5. Restart.
> 6. Voilà.

where is settings.json??????
