### ISSUE TITLE
Feature request: Inline css-rules

### ISSUE THREAD

**Issue by m-thorsen** [be5invis/vscode-custom-css#42]
For those of us who only add a few css rules it would be nice to not need a separate css file. This would also work well in combination with Settings Sync and similar extensions.

Suggested syntax: 

```json
"vscode_custom_css.rules": {
  "monaco-workbench.linux": {
     "-webkit-text-stroke": "0.25px"
  },
  ".monaco-tree-row.has-children": {
     "font-weight": "bold"
  }
}, ...
```

...would then generate an inline style tag:

```html
<style type="text/css" class="contributedColorTheme">
monaco-workbench.linux {
  -webkit-text-stroke: 0.25px !important;
}
.monaco-tree-row.has-children {
  font-weight: bold !important;
}
</style>
```

**Comment by be5invis** [comment]
Honestly this way does not work, because how this plugin works is it modifies VSCode’s installation directly, inject JS and CSS into it (so that is why Code complains about that itself is broken after CSS/JS is applied).

发自我的 iPhone

在 2018年5月24日，19:51，m-thorsen <notifications@github.com<mailto:notifications@github.com>> 写道：


For those of us who only add a few css rules it would be nice to not need a separate css file. This would also work well in combination with Settings Sync and similar extensions.

Suggested syntax:

"vscode_custom_css.rules": {
  "monaco-workbench.linux": {
     "-webkit-text-stroke": "0.25px"
  },
  ".monaco-tree-row.has-children": {
     "font-weight": "bold"
  }
}, ...

...would then generate an inline style tag:

<style>
monaco-workbench.linux {
  -webkit-text-stroke: 0.25px !important;
}
.monaco-tree-row.has-children {
  font-weight: bold !important;
}
</style>
