### ISSUE TITLE
Where I can find the css file!

### ISSUE THREAD

**Issue by khaled9544** [be5invis/vscode-custom-css#56]
Hello,

Where I find the css file in order to import it in the `vscode_custom_css.imports`?!

Thanks.

**Comment by be5invis** [comment]
Write your own.


________________________________
收件人: khaled9544 <notifications@github.com>
发送时间: 星期日, 十二月 2, 2018 20:16
收件人: be5invis/vscode-custom-css
抄送: Subscribed
主题: [be5invis/vscode-custom-css] Where I can find the css file! (#56)


Hello,

Where I find the css file in order to import it in the vscode_custom_css.imports?!

Thanks.

―

**Comment by sidrk** [comment]
You can go to Help -> Developer Tools to open the inspector to get started on styling the components you want, for example if I wanted to style the font for all the text, I could write something simple like

```css
.monaco-workbench {
    font-family: 'Arial', sans-serif;
}
```
