### ISSUE TITLE
Linux manjaro unable to claim ownership over vscode

### ISSUE THREAD

**Issue by Kaesebrot84** [be5invis/vscode-custom-css#76]
My vscode installation is located at `/usr/bin/code` (via `which code`). If try to take ownership with `sudo chown -R $(whoami) /usr/bin/code` I still cannot reload  "Custom CSS and JS"

![image](https://user-images.githubusercontent.com/13865115/57395338-2d5d5500-71c8-11e9-8e48-23e9fe44d78d.png)

Any ideas?

**Distribution:** ManjaroLinux
**Distribution Release:** 18.0.4

**Comment by TheManticore** [comment]
Manjaro (like Arch) creates a symlink at /usr/bin/code.
You'll want to follow the Arch instructions and use `sudo chown -R $(whoami) /opt/visual-studio-code/` to set the correct permissions.

**Comment by roachsinai** [comment]
Using Manjaro, install code oss version,  

`lrwxrwxrwx 1 roach root 17  4月 12 16:50 /usr/bin/code -> /usr/bin/code-oss`

sudo use `sudo chown -R $(whoami) /usr/bin/code-oss` to chown, but still not work! Got thing same with the screenshot like @Kaesebrot84 posted.

**Comment by nerdyman** [comment]
I'm also getting this issue on vanilla Arch.

These are the settings I'm using:

```json
{
    "vscode_custom_css.imports": [
        "file:///home/me/.config/__custom/vscode-style.css",
    ],
    "vscode_custom_css.policy": true,
}
```

These are the permissions of `~/.config__custom`

```
drwxr-xr-x 1 me me   32 Jun  6 11:30 .
drwx------ 1 me me 1020 Jun  6 11:30 ..
-rwxr-xr-x 1 me me  348 Jun  6 11:30 vscode-style.css
```

Also not sure if it's the same on Manjaro but Arch installs vscode to `/usr/lib/code`.

The owner of `/home/me/.config/__custom` is the same user I'm running vscode as. I haven't changed ownership or permissions of vscode itself as root `0755` seems sensible for `/usr/lib`.

**Comment by EralpCelebi** [comment]
Has anybody found a solution to this?

**Comment by EralpCelebi** [comment]
I think I found a solution :p
as @nerdyman said Manjaro tends to install code in `/usr/lib/code` with binaries being located in `/usr/bin/code` and `/usr/bin/code-oss`

So to chown the necessary files you have to use these commands:
`
sudo chown -R $(whoami) /usr/bin/code
sudo chown -R $(whoami) /usr/bin/code-oss
sudo chown -R $(whoami) /usr/lib/code
`
I don't know if this is a global solution but I got it to work by executing these commands.

**Comment by Delphinidae84** [comment]
@EralpCelebi I will try this on my machine, thanks!

**Comment by Kaesebrot84** [comment]
@EralpCelebi your solution solved my problem, thanks.

**Comment by Razzeee** [comment]
Might be good to have this referenced in the readme somehow.

**Comment by witt-bit** [comment]
> I think I found a solution :p as @nerdyman said Manjaro tends to install code in `/usr/lib/code` with binaries being located in `/usr/bin/code` and `/usr/bin/code-oss`
> 
> So to chown the necessary files you have to use these commands:
> 
> ```
> sudo chown -R $(whoami) /usr/bin/code
> sudo chown -R $(whoami) /usr/bin/code-oss
> sudo chown -R $(whoami) /usr/lib/code
> ```
> 
> I don't know if this is a global solution but I got it to work by executing these commands.

I executed your command on my machine, but it didn't solve my problem. I installed https://aur.archlinux.org/packages/visual-studio-code-bin. I found that the minimum command needed to be executed was sudo chown -R $(whoami) /opt/visual-studio-code/resources. If sudo chown -R $(whoami) /opt/visual-studio-code is executed, it will trigger the error "Your Code installation appears to be corrupt. Please reinstall." The error comes from https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported

I think we should solve the problem from the source, rather than manually solving it again after each update

1. Suggest to the AUR author to have the correct ownership of some directories during installation. I commented to the author and was rejected

2. Please provide the minimum installation file that needs to be authorized to avoid triggering the error "Your Code installation appears to be corrupt. Please reinstall."

**Comment by witt-bit** [comment]
> I think I found a solution :p as @nerdyman said Manjaro tends to install code in `/usr/lib/code` with binaries being located in `/usr/bin/code` and `/usr/bin/code-oss`
> 
> So to chown the necessary files you have to use these commands:
> 
> ```
> sudo chown -R $(whoami) /usr/bin/code
> sudo chown -R $(whoami) /usr/bin/code-oss
> sudo chown -R $(whoami) /usr/lib/code
> ```
> 
> I don't know if this is a global solution but I got it to work by executing these commands.

I executed your command on my machine, but it didn't solve my problem. I installed https://aur.archlinux.org/packages/visual-studio-code-bin . I found that the minimum command needed to be executed was `sudo chown -R $(whoami) /opt/visual-studio-code/resources`. If `sudo chown -R $(whoami) /opt/visual-studio-code` is executed, it will trigger the error "Your Code installation appears to be corrupt. Please reinstall." The error comes from https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported

I think we should solve the problem from the source, rather than manually solving it again after each update

1. Suggest to the AUR author to have the correct ownership of some directories during installation. I commented to the author and was rejected

2. Please provide the minimum installation file that needs to be authorized to avoid triggering the error "Your Code installation appears to be corrupt. Please reinstall."

**Comment by witt-bit** [comment]
> > I think I found a solution :p as @nerdyman said Manjaro tends to install code in `/usr/lib/code` with binaries being located in `/usr/bin/code` and `/usr/bin/code-oss`
> > So to chown the necessary files you have to use these commands:
> > ```
> > sudo chown -R $(whoami) /usr/bin/code
> > sudo chown -R $(whoami) /usr/bin/code-oss
> > sudo chown -R $(whoami) /usr/lib/code
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know if this is a global solution but I got it to work by executing these commands.
> 
> I executed your command on my machine, but it didn't solve my problem. I installed [aur.archlinux.org/packages/visual-studio-code-bin](https://aur.archlinux.org/packages/visual-studio-code-bin) . I found that the minimum command needed to be executed was `sudo chown -R $(whoami) /opt/visual-studio-code/resources`. If `sudo chown -R $(whoami) /opt/visual-studio-code` is executed, it will trigger the error "Your Code installation appears to be corrupt. Please reinstall." The error comes from [code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported](https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported)
> 
> I think we should solve the problem from the source, rather than manually solving it again after each update
> 
> 1. Suggest to the AUR author to have the correct ownership of some directories during installation. I commented to the author and was rejected
> 2. Please provide the minimum installation file that needs to be authorized to avoid triggering the error "Your Code installation appears to be corrupt. Please reinstall."

Information about my machine

```shell
~  screenfetch                                                                                                                                                   ✔ 

 ██████████████████  ████████     witt@witt-cool
 ██████████████████  ████████     OS: Manjaro 24.1.1 Xahea
 ██████████████████  ████████     Kernel: x86_64 Linux 6.10.11-2-MANJARO
 ██████████████████  ████████     Uptime: 2d 25m
 ████████            ████████     Packages: 1336
 ████████  ████████  ████████     Shell: zsh 5.9
 ████████  ████████  ████████     Resolution: 3840x1080
 ████████  ████████  ████████     DE: KDE
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Adwaita-dark [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Tela-circle-manjaro-light
 ████████  ████████  ████████     Disk: 105G / 467G (24%)
 ████████  ████████  ████████     CPU: AMD Ryzen 5 4500U with Radeon Graphics @ 6x 2.375GHz
 ████████  ████████  ████████     GPU: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.57, 6.10.11-2-MANJARO)
                                  RAM: 9163MiB / 15359MiB
```
