### ISSUE TITLE
Mac OS - Run VS Code with admin privileges so the changes can be applied

### ISSUE THREAD

**Issue by ZXMLoveCXF** [be5invis/vscode-custom-css#85]
![image](https://user-images.githubusercontent.com/16054246/59666149-ddba7200-91e6-11e9-8784-37202dd881a8.png)
So what should I do?
macOS

**Comment by ZXMLoveCXF** [comment]
![image](https://user-images.githubusercontent.com/16054246/59668109-7bfc0700-91ea-11e9-8510-45c701f59a1a.png)

**Comment by dangh** [comment]
@ZXMLoveCXF you need to run it from terminal like
`sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

**Comment by ZXMLoveCXF** [comment]
> @ZXMLoveCXF you need to run it from terminal
> `sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

What do you mean that every time I open a vscode, I need to open it from the terminal?

**Comment by dangh** [comment]
@ZXMLoveCXF no you only need to do it once.

As VS Code doesn’t have an option to load external CSS, this extension will patch VS Code application (in `/Applications/Visual Studio Code.app/Content/…`) to include your CSS file. In order to do that, it need to be run as administrator.

Once the app has been patched, you can run it normally.

If you update VS Code, or change the CSS/JS file location, you need to run it as administrator again.

**Comment by ZXMLoveCXF** [comment]
> @ZXMLoveCXF no you only need to do it once.
> 
> As VS Code doesn’t have an option to load external CSS, this extension will patch VS Code application (in `/Applications/Visual Studio Code.app/Content/…`) to include your CSS file. In order to do that, it need to be run as administrator.
> 
> Once the app has been patched, you can run it normally.
> 
> If you update VS Code, or change the CSS/JS file location, you need to run it as administrator again.

thank you very much!

**Comment by boneskull** [comment]
I keep getting this message.  I've tried running VS Code via `sudo` (as noted above), but this only temporarily removes the message.

My `Visual Studio Code.app` is installed by homebrew into `~/Applications`; my user is the owner of everything in this directory.

The only error in my console is:

![image](https://user-images.githubusercontent.com/924465/65985358-71324e80-e436-11e9-9f6f-861af5215752.png)

which seems unrelated.

Regardless, the custom CSS seems to work fine, so I'm not sure what the issue is.

**Comment by RezhaBlue** [comment]
I'm running into the same issue, this was closed with no explanation or anyone addressing it.
I have tried both wsl (`sudo /c/Program\ Files/Microsoft\ VS\ Code/bin/code`) and windows using run as admin respectively but the extension continues to assert I need to run vs code with admin privileges. This seems like a bug to me.

**Comment by chobijaeyu** [comment]
> @ZXMLoveCXF you need to run it from terminal
> `sudo /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

after command `Enable Custom CSS and JS` and restart vscode
I get this error 
`Your Code installation appears to be corrupt. Please reinstall.`

**Comment by Kwaadpepper** [comment]
This happens all the time, same issue here on linux.
Chmoded  vscode install dir ```/usr/share/code```, changes are applied.

Still this annoying notification appears...
